### ISSUE TITLE
Password parse error

### ISSUE THREAD

**Issue by HardRock4Life** [CrunchyData/pg_tileserv#100]
Hello!

My password contains a number sign (#), I can't change it, but I can't properly write it in the cmd neither.

What happens - the parser simply changes it into the backslash (\), so the password becomes incorrect.

Adding another backslash as an escape character produces even more backslashes.

I can tell you this sure because connection to my local database runs fine, and its password doesn't contain the number sign. The dollar sign ($) work fine, btw.

So, the question is: can I parse the password the way the number sign fits in correctly?

**Comment by pramsey** [comment]
Replace the `#` with the url encoded form for `#`, namely `%23`. Seems to work for me. The problem seems restricted to the golang libpq implementation, the native C implementation was quite happy to deal with the # in the database URL.
