### ISSUE TITLE
"ERROR: Missing libprotobuf-c (SQLSTATE XX000)"

### ISSUE THREAD

**Issue by HardRock4Life** [CrunchyData/pg_tileserv#101]
Hello!

I ran into this issue when I tried to open my data from PostgreSQL. 

Tried to build a protobuf compiler by following similar commands with Linux installation instructions, re-installed PostGIS Bundle, but it did not really work out.

For demo data, there is no such reaction.

How to ensure that pg_tileserv sees the libprotobuf-c library ?

**Comment by bthomasaevex** [comment]
idk if anyone else is looking for a solution to this, but just in case...

1. install libprotobuf-c (sudo apt-get or build from their github)
2. pull down PostGIS's github and build, it'll link with the libprotobuf now
3. sudo ldconfig

Now when pg_tileserv uses PostGIS, it'll recognize libprotobuf isn't missing
