### ISSUE TITLE
Error when trying to build Dockerfile

### ISSUE THREAD

**Issue by AnnieGitUrGun** [CrunchyData/pg_tileserv#106]
When I run the following:

```
export VERSION="latest-alpine-3.12"
docker build --build-arg VERSION=${VERSION} -t pramsey/pg_tileserv:${VERSION} .
```

I get an error: `ERROR [stage-0 5/5] RUN go build -v -ldflags "-s -w -X main.programVersion=latest-alpine-3.12"`

And the following message:

```
[stage-0 5/5] RUN go build -v -ldflags "-s -w -X main.programVersion=latest-alpine-3.12":
#13 0.363 package .: no Go files in /app
```

Am I doing something wrong? I've tried building it without specifying a version and I get the same error.

**Comment by pramsey** [comment]
Check the Makefile, there should be a magic incantation in there for build. Or just use the version on dockerhub.

**Comment by AnnieGitUrGun** [comment]
User error on my part. Thanks for your help!
