### ISSUE TITLE
error: "ERROR: transform: tolerance condition error (-20) (SQLSTATE XX000)"

### ISSUE THREAD

**Issue by afau12991** [CrunchyData/pg_tileserv#109]
Hi! I am consistently getting the following error when fetching shapes: 
`ERROR: transform: tolerance condition error (-20) (SQLSTATE XX000)`

This is consistently happening when the SRID env is set to 3857 for shapes closest to the south pole. I have tested passing in an SRID and Xmin, Ymin etc for SRID 4326, and shapes load fine. I unfortunately can't use this because bounds must be a square (tested w/ Xmin: -90, Ymin: -90, Xmax: 90, Ymax: 90 just to understand behavior).

I've been doing a bit of research on the issue and have found several sources that say that Web Mercator Projection can't show data near poles. The problem & solution mentioned here describe what I am experiencing: https://gis.stackexchange.com/questions/357847/postgis-vector-tiles-zoom-affects-tile-production

Trying to understand how best to get past this issue. Thanks

**Comment by pramsey** [comment]
Sorry, it's just math. There's not a projection that's going to look shape-preserving and also give you full coverage of the world. If you are working on a *particular* pole, you can use polar stereographic. If you want something world-wide you have to settle for the non-square 4326 and just suck up the shape distortions (or write your own renderer to dynamically project into an orthographic or something as you zoom)
