### ISSUE TITLE
PgBouncer support

### ISSUE THREAD

**Issue by BuriedStPatrick** [CrunchyData/pg_tileserv#111]
I'm wondering whether there's any specific configuration for PgBouncer support? From [the docs][1] I can't seem to find any ways to change so that we can leverage the connection pools management on the server side using PgBouncer.

If I, rather naively, try to run the connection through PgBouncer, I get the following error:

```
 level=fatal msg="ERROR: prepared statement \"lrupsc_1_1\" already exists (SQLSTATE 42P05)"
```

Seems to be an issue regarding prepared statements on a PgBouncer connection. So I'm wondering if there's a way to switch it to "describe mode" as [pointed out here][2]?

Full log:

```
time="2021-09-24T08:52:05Z" level=info msg="pg_tileserv latest"
time="2021-09-24T08:52:05Z" level=info msg="Run with --help parameter for commandline options"
time="2021-09-24T08:52:05Z" level=info msg="Using database connection info from environment variable DATABASE_URL"
time="2021-09-24T08:52:05Z" level=info msg="Using config file: /config/pg_tileserv.toml"
time="2021-09-24T08:52:05Z" level=info msg="Serving HTTP  at http://0.0.0.0:7800/"
time="2021-09-24T08:52:05Z" level=info msg="Serving HTTPS at http://0.0.0.0:7801/"
time="2021-09-24T08:52:05Z" level=info msg="Using CoordinateSystem.SRID 3857 with bounds [-2.00375083427892e+07, -2.00375083427892e+07, 2.00375083427892e+07, 2.00375083427892e+07]"
time="2021-09-24T08:52:05Z" level=info msg="Connected as 'REDACTED' to 'REDACTED' @ 'REDACTED'"
time="2021-09-24T08:52:05Z" level=fatal msg="ERROR: prepared statement \"lrupsc_1_1\" already exists (SQLSTATE 42P05)"
```

[1]: https://access.crunchydata.com/documentation/pg_tileserv/1.0.8/installation/
[2]: https://github.com/jackc/pgx/issues/602#issuecomment-532236718

**Comment by pramsey** [comment]
I'll have a look-see. Probably need to do a little patch.

**Comment by pramsey** [comment]
I haven't been able to reproduce this. Just using the latest pg_bouncer from the web site. Is this using pgbouncer with some non-default configuration in the config file?
