### ISSUE TITLE
lcc projection

### ISSUE THREAD

**Issue by wendellwt** [CrunchyData/pg_tileserv#113]
How do I use pg_tileserv to serve vector tiles in Lambert Conformal Conic?

I would like to serve LCC vector tiles for the continental United States, with the server doing the reprojection.  Does it make sense to do this in the server?  Or is that a client issue (in this case openlayers)?

Can I set the SRID in the CoordinateSystem section to ESRI:102004?  Does that field accept proj4 strings so I can set lat_1, lat_2, and lon_0?

Thank you,
Wendell

**Comment by pramsey** [comment]
(a) You can set the SRID to any number that exists in the `spatial_ref_sys` table. So fill in an entry, if one doesn't already exist, with valid values for the srtext, proj4text, etc.
(b) You *must* also set up the xmin/ymin/xmax/ymax values to the (square) extents of your zoom=0 tile, and you have to match up those settings in openlayers.

**Comment by pramsey** [comment]
Dupes #117
