### ISSUE TITLE
Starting with Tileserv. Only one table exposed

### ISSUE THREAD

**Issue by ftayyab** [CrunchyData/pg_tileserv#114]
Hi,

i am trying to run postgis and tileserv image on docker (locally). I have been able to run the two containers however, when checking localhost:7800, I can only see single table. I am using default postgis image hence it has the tiger schema that has many tables. Not sure why only one table is being picked up by tileserv and why not all?

Any ideas?

**Comment by pramsey** [comment]
The only tables that will be visible by default are those with (a) a geometry column that (b) has a defined geometry type (point/linestring/polygon) in the column typedef and (c) has a defined SRID in the column typedef. If you run `SELECT * FROM GEOMETRY_COLUMNS` on the database, you should see entries with something other than "GEOMETRY" in the `type` column and something other than 0 in the `srid` column.
