### ISSUE TITLE
feature limit at layer extent

### ISSUE THREAD

**Issue by joekbullard** [CrunchyData/pg_tileserv#116]
I've been experimenting with pg_featureserv running on an AWS EC2 instance recently where one of my use cases involves loading the data as a was layer as per [this tutorial](https://blog.crunchydata.com/blog/using-postgis-and-pg_featureserv-with-qgis). My postgis table contains around 4900 rows of point data, however I have noticed that pg_featureserv seems to only render a maximum of 1000 features when zoomed to layer extent in qgis. Similarly, when viewing using `[aws-ec2-url]:9000/collections/public.tree_preservation_order_trunk/items.html?limit=5000` it still only renders 1000 (see image). Strangely when zoomed in slightly using qgis, this number will increase to around 1700. I can't quite figure out what exactly is going on in this case. Is this a bug? or perhaps I'm missing something fundamental?

<img width="880" alt="Screenshot 2021-10-24 at 12 46 29" src="https://user-images.githubusercontent.com/35529853/138592855-7dc054b5-a3e2-4e4c-a7ed-99475ebe2b14.png">
<img width="792" alt="Screenshot 2021-10-24 at 12 49 42" src="https://user-images.githubusercontent.com/35529853/138592856-e0ec8936-4c57-47a3-b470-c616f0f39430.png">
<img width="793" alt="Screenshot 2021-10-24 at 12 51 41" src="https://user-images.githubusercontent.com/35529853/138592857-4601e164-14bf-4433-aff9-57548fb7bf91.png">

**Comment by arkeri** [comment]
@joekbullard were you able to expose a public endpoint from your ec2? we are currently unable to do this and desperate to make it work
