### ISSUE TITLE
Raster Support

### ISSUE THREAD

**Issue by ajitrAppcino** [CrunchyData/pg_tileserv#119]
Is there any support for raster files. I want to serve them as layers through postGIS.
If not how can I serve raster file from postGIS onto my Map.

**Comment by pramsey** [comment]
There is not support, these are vector tiles. You'll need a server that understands PostGIS raster. I think MapServer.org does.

**Comment by muety** [comment]
I see that this is beyond the scope of this project, but I'd love to have a simple, easy-to-use raster server for PostGIS, that reads `raster` data and returns tiles or WMS. I tried MapServer and Geoserver, but both are super hard to set up and feel quite heavyweight. Is something like this planned for the CrunchyData ecosystem?
