### ISSUE TITLE
a simple question

### ISSUE THREAD

**Issue by mustafautku** [CrunchyData/pg_tileserv#120]
Hi,
I liked pg_tile server and I want to use it. But I have simple ( I think very simple :)) question.

pg_tile server runs well. for example:
http://0.0.0.0:7800/public.property_addresses.html  works and displays the map. I can zoom in or out. 

But when I enter  a pbf file in url it says 404 page not found..
For example: when I enter 
http://0.0.0.0:7800/public.property_addresses/{z}/{x}/{y}.pbf  
or 
http://0.0.0.0:7800/public.property_addresses/0/0/0.pbf  it says:
404 page not found.  My browser does not display anything, 
What am I doing wrong? 

thanks for the help.

**Comment by pramsey** [comment]
I'm not seeing the same thing... 
```
curl -I http://0.0.0.0:7800/public.bc_polls_2020/0/0/0.pbf

HTTP/1.1 200 OK
Content-Type: application/vnd.mapbox-vector-tile
Vary: Accept-Encoding
Date: Sun, 21 Nov 2021 21:35:47 GMT
```

If you watch the map load using the network activity viewer in your browser can you hit the URLs that the map is loading directly?

**Comment by mustafautku** [comment]
Yes,
curl's output is OK.
But, I am sorry I cannot follow the point in your last sentence. Do you mean I cannot enter http://...pbf directly in the browser? 
I can see pg_tileser's network activity in its console such as   GET /public....../2/0/0.pbf. It is apparent that this is generated automatically somewhere. I do not know why I am trying this. I just want to understand some behind the scene. But I cannot enter this as URL. 
I am not a web developer, but just want to visualize my spatial data and apply some query capabilities on the map. ( ı think I need pg_featureserv for this by the way..)
Thanks for any more clarification or additional useful documentation to understand more.

**Comment by pramsey** [comment]
Does the curl trick work for you? Then all is well, and there is something
odd with your browser

**Comment by mustafautku** [comment]
Yes it works. Thanks for your comments.
