### ISSUE TITLE
Alias for multi-layer tiles

### ISSUE THREAD

**Issue by alfmarcua** [CrunchyData/pg_tileserv#121]
Multi-layer tiles approach of #115 is a huge improvement. However, having several layers results in long urls that may reach to the 2048 characters, especially when you also have some parameters.

Therefore, it would be great if an alias could be set for multi-layer tiles. Hence, the corresponding url will be shortened.

**Comment by pramsey** [comment]
Write a function that composes the multi-layer tile of your dreams :)
