### ISSUE TITLE
Function Layers - How to use config SRID?

### ISSUE THREAD

**Issue by m9brady** [CrunchyData/pg_tileserv#122]
Hi there,

Thank you for pg_tileserv, it has been really nice to experiment with and the crazy-low barrier-to-entry for PostGIS novices is very much appreciated.

I have had great success serving tiles from a Table Layer with a custom SRID (see below config defn.) but am running into issues when trying to render the results of a Function Layer. I've been trying to adapt the [examples given](https://access.crunchydata.com/documentation/pg_tileserv/latest/usage/function-layers/) (thank you) and the date-filter query is  valid but I think the way I'm doing the `ST_AsMVTGeom` is flawed. I've been banging my head against the wall trying to figure out the issue and began to wonder if it is just not currently possible for a function layer to respect the config SRID?

One thing I noticed is that for the pg_tileserve Table Layer there is a defined `center` and `bounds` (strange to me that they're not in SRID:3413!):
```json
{
  "center": [-45.24930531059953,49.34109101876729],
  "bounds": [-172.9258453985025,43.316419251717335,82.42723477730344,55.36576278581723]
}
```

...but for the Function Layer there are no such attributes defined. Are these integral to pg_tileserv? Is there a way to define these in the function SQL or in pg_tilserv config? Or should I somehow dynamically define the center/bounds in the Tile Layer JS (currently using OpenLayers)? Should I look into using a different tile server? (I like this one too much!) Any general tips/advice are also appreciated.

Here is the function SQL I've been clumsily mashing together:
```sql
CREATE OR REPLACE
FUNCTION sar.s1_filter_by_date(
            z integer, x integer, y integer,
            ts date default '2020-11-13')
RETURNS bytea
AS $$
    -- Convert tile coordinates to a bounding box 
    WITH
    bounds AS (
    SELECT ST_TileEnvelope(z, x, y) AS geom
),
    -- Convert raw geometry into MVT geometry
    -- Pull just the img_src in addition to the geometry
    -- Apply the ts parameter to the WHERE clause
    mvtgeom AS (
        SELECT ST_AsMVTGeom(ST_Transform(t.geom, 3413), bounds.geom) AS geom,
            t.img_src
        FROM sar.s1 t, bounds
        WHERE ST_Intersects(t.geom, ST_Transform(bounds.geom, 3413))
        AND TO_DATE(SUBSTRING(t.img_src, '([0-9]{14})'), 'YYYYMMDDHH24MISS') = ts
    )
    -- Serialize the result set into an MVT object
    SELECT ST_AsMVT(mvtgeom, 'sar.s1_filter_by_date') FROM mvtgeom;
$$
LANGUAGE 'sql' STABLE PARALLEL SAFE;
```

### config.toml SRID definition
*Same as the data in PostGIS. All other items are defaults*
```toml
[CoordinateSystem]
SRID = 3413
Xmin = -6000000
Ymin = -6000000
Xmax =  6000000
Ymax =  6000000
```

### Current Function Layer Result (OpenLayers)
![image](https://user-images.githubusercontent.com/5256866/151666062-0d4d2cad-b935-4a5e-99e8-d52b2773af53.png)

### Expected Function Layer Result using default date
![image](https://user-images.githubusercontent.com/5256866/151666014-6c046fd4-0583-40f7-b98a-72ec8412fa11.png)

**Comment by pramsey** [comment]
I can provide some hints which will maybe help you get there. First, you use [ST_TileEnvelope](https://postgis.net/docs/ST_TileEnvelope.html) to get a bounds... what CRS will those bounds be in? By default, web mercator, so you need to get bounds that make sense for your application projection. You already have the ones you are using in your config file, so you need to bring those into your tile envelope creation. There's even an extra bounds parameter there you can use to both set the bounds and the output SRID, if I'm not mistaken.

Once you're pulling the right tile, in the right plane you're getting closer, and you'll want to make sure you also pass the tile bounds into the AsMVTGeom call, since that function needs to know what box to normalize the data into. At that point you should hopefully be generating tiles that are properly located to fit into your mapping application (assuming you've successfully got your application working with table-level non-mercator projections, which can be its own little dance of pain for different web map libraries).

**Comment by m9brady** [comment]
🤦‍♂️ I wasn't even considering a problem with `ST_TileEnvelope` but one little SQL change and it works beautifully now. I appreciate your time, patience and expertise!

Fixed SQL:
```diff
CREATE OR REPLACE
FUNCTION sar.s1_filter_by_date(
            z integer, x integer, y integer,
            ts date default '2020-11-13')
RETURNS bytea
AS $$
    -- Convert tile coordinates to a bounding box 
    WITH
    bounds AS (
-        SELECT ST_TileEnvelope(z, x, y) AS geom
+        SELECT ST_TileEnvelope(z, x, y, ST_MakeEnvelope(-6000000, -6000000, 6000000, 6000000, 3413)) AS geom
),
    -- Convert raw geometry into MVT geometry
    -- Pull just the img_src in addition to the geometry
    -- Apply the ts parameter to the WHERE clause
    mvtgeom AS (
        SELECT ST_AsMVTGeom(t.geom, bounds.geom) AS geom,
            t.img_src
        FROM sar.s1 t, bounds
        WHERE ST_Intersects(t.geom, bounds.geom)
        AND TO_DATE(SUBSTRING(t.img_src, '([0-9]{14})'), 'YYYYMMDDHH24MISS') = ts
    )
    -- Serialize the result set into an MVT object
    SELECT ST_AsMVT(mvtgeom, 'sar.s1_filter_by_date') FROM mvtgeom;
$$
LANGUAGE 'sql' STABLE PARALLEL SAFE;
```

**Comment by pramsey** [comment]
Wow, that's gratifying it was a two-liner!
