### ISSUE TITLE
URL of layer.json metadata

### ISSUE THREAD

**Issue by KoalaGeo** [CrunchyData/pg_tileserv#125]
Hi, 

I'm trying to connect pg_tileserv to pygeoapi to offer OGCAPI-Tiles. 

pg_tileserv puts the layer metadata at http://baseurl/bedrock_geology.json, However pygeoapi is expecting it located at http://baseurl/bedrock_geology/metadata.json (specifically "metadata.json" the same as generated if using tippecanoe)

I did want to amend pygeoapi so the metadata location could be specified https://github.com/geopython/pygeoapi/pull/821 however it's currently beyond my python capabilities. 

Might it be possible to update the default layer metadata path in pg_tileserv to match that expected by pygeoapi?

**Comment by pramsey** [comment]
Eventually, maybe? I haven't even read the spec, thus far. If there's finally clients that might use it, that increases the odd. And of course, contributions are welcome.

**Comment by pramsey** [comment]
Going to close this in favour of #126
