### ISSUE TITLE
Docker ARM build

### ISSUE THREAD

**Issue by aberenyi** [CrunchyData/pg_tileserv#127]
It would be really nice to have arm builds on docker hub.

Is this something that you can add to the roadmap?

Cheers

**Comment by pramsey** [comment]
Nope! I have no ARM system to test with and no way to validate it and no particular knowledge of the magic incantations to generate an ARM docker build. A PR from someone who has done the necessary work to get it going would be appreciated.

**Comment by khanziaullah** [comment]
We have one image here:

https://hub.docker.com/repository/docker/zasmlabs/pg_tileserv

Will share our tests results. 
Built it on Beaglebone Black Rev C.
Linux beaglebone 4.19.94-ti-r73 #1buster SMP PREEMPT Fri Apr 15 21:38:30 UTC 2022 armv7l GNU/Linux
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
