### ISSUE TITLE
Server hangs on startup

### ISSUE THREAD

**Issue by bogind** [CrunchyData/pg_tileserv#128]
Using the windows latest (Guessing 1.0.8 based on the last release) under win10 OS.
Started the server for the first time under `localhost` and `http://localhost:7800` just kept loading.

I am behind an organizational proxy, but that shouldn't have made a difference, just kept loading for about 20 minutes without timeout.
`http://localhost:7801` got a timeout.

Eventually got a result after pressing <kbd>Ctrl</kbd>+<kbd>C</kbd> and server started working (without a restart).
You can see the time gap between "Serving HTTP at 0.0.0.0:7800" and the first GET request which I started almost when the server went up.

The database connected has only about 30 layers in case the number of layers makes a difference, most of which (25) are Natural Earth.
![image](https://user-images.githubusercontent.com/26594971/153128245-1f26d313-519d-412d-aebb-92518f74654b.png)

**Comment by pramsey** [comment]
Some more work on checking if this always recurs, or if it's tied to number of layers would be appreciated, otherwise you're delegating to me to try and recreate your scenario.
