### ISSUE TITLE
Add CQL Filters

### ISSUE THREAD

**Issue by pramsey** [CrunchyData/pg_tileserv#129]
pg_featureserv has just gotten CQL filtering, this seems like a nice possible way to expose filtering without requiring function building or a bunch of bespoke APIs for different kinds of filters. One API, all kinds of filters.

**Comment by dr-jts** [comment]
`pg_featureserv` [PR-101](https://github.com/CrunchyData/pg_featureserv/pull/101).

The CQL implementation is in the [`cql`](https://github.com/CrunchyData/pg_featureserv/tree/master/internal/cql) dir.  Entry point is [`cql.TranspileToSQL`](https://github.com/CrunchyData/pg_featureserv/blob/master/internal/cql/cql.go#L11).

**Comment by dr-jts** [comment]
Fixed by #130.
