### ISSUE TITLE
Windows version detected as virus

### ISSUE THREAD

**Issue by gmonk** [CrunchyData/pg_tileserv#132]
Why would pg_tileserver.exe be detected as malicious from both norton and cylance

downloaded from https://postgisftw.s3.amazonaws.com/pg_tileserv_latest_windows.zip

Cylance

Unsafe
MaxSecure

Trojan.Malware.300983.susgen

**Comment by robe2** [comment]
FWIW I scanned the windows zip with MS Windows Defender and it did not detect any virus

I think some  virus checkers are overzealous and might flag anything that has network bits like https/curl etc as virus.
Go binaries I think are especially flagged.

**Comment by pramsey** [comment]
Makes sense, go would be useful for multiplatform virus payloads.

**Comment by gmonk** [comment]
I think you are right. I did some looking into Cylance and it seems this particular AV is known for false positives. Thanks for the feed back
