### ISSUE TITLE
Multiple Layers Question

### ISSUE THREAD

**Issue by gmonk** [CrunchyData/pg_tileserv#133]
Is it possible to create  a base map using pg_tileserv ?  I have been scouring the internet and it seems there are so many different ways its making my head spin.  I'm trying to achieve something similar to the following https://www.arcgis.com/apps/mapviewer/index.html?layers=86f556a2d1fd468181855a35e344567f     My goal is to have a decent base map  that I can overlay near real-time data over. The data is just a geojson feature that gets updated at regular intervals. I have imported arizona-latest.osm.pbf into postgis using imposm   which produces several tables and I'm not sure if its possible to serve all of these with pg_tileserv or if this is the best approach perfomance wise.  Sorry for the noob questions.

Thanks for the help

**Comment by pramsey** [comment]
I suppose it is "possible", but I wouldn't try it personally. pg_tileserv is more aimed at serving a dynamic layer than might lay on *top* of a base map. For base maps, I personally would work with the tools at https://openmaptiles.org/
