### ISSUE TITLE
Functional layers not rendering in UI

### ISSUE THREAD

**Issue by wichert** [CrunchyData/pg_tileserv#134]
I made a functional layer to allow filtering of data using optional parameters. To do this I have a view which returns all data, and a function based on the [advanced functional layer](https://access.crunchydata.com/documentation/pg_tileserv/latest/usage/function-layers-advanced/). The resulting layer looks fine if I test it with curl and looking at the result with `ogrinfo -al`. I can also add the layer in qgis and view it in there. Looking at the layer in pg_tileserv's UI does not work: I can see the browser loading valid data from pg_tileserv, but nothing appears on the map. Loading the exact same data using the view used by the SQL function works fine.

<details>
<summary>SQL function</summary>
Here is the code for our SQL function:

```sql
CREATE OR REPLACE FUNCTION lane_boundary(z integer, x integer, y integer, map_version integer DEFAULT NULL::integer)
    RETURNS bytea
    LANGUAGE plpgsql
    IMMUTABLE
    STRICT
    PARALLEL SAFE
AS $function$
DECLARE
    result bytea;
    bounds geometry;
    mvt_title text;
BEGIN
    SELECT ST_TileEnvelope (z, x, y) AS geom
    INTO bounds;

    SELECT mvt_pick_map_version(map_version)
    INTO map_version;

    SELECT 'lane_boundary ' || title
    INTO mvt_title
    FROM supplier_map_version
    WHERE supplier_map_version.id = map_version;

    EXECUTE
        'WITH mvtgeom AS ('
        'SELECT'
        '    t.id,'
        '    t.nds_tile_id,'
        '    t.lane_group_id,'
        '    t.lane_id,'
        '    t.boundary_id,'
        '    t.boundary_geometry_id,'
        '    ST_AsMVTGeom (ST_Transform (t.geom, 3857), $2) AS geom '
        'FROM'
        '    export_lane_boundary t '
        'WHERE'
        '    ST_Intersects (t.geom, ST_Transform ($2, 4326))'
        '    AND t.map_version_id=$1'
        ')'
        'SELECT'
        '    ST_AsMVT (mvtgeom, $3)'
        'FROM mvtgeom'
    INTO STRICT result
    USING map_version, bounds, mvt_title;

    RETURN result;
END;
$function$;
```
</details>

**Comment by autra** [comment]
I have the same problem. The layer name must be the same as the fully qualified function name (according to my tests). So I guess you cannot use ` SELECT 'lane_boundary ' || title` here.

**Comment by autra** [comment]
Or another possible fix would be to somehow detect that and change the layer id in mapbox config.

**Comment by autra** [comment]
Note : PR #135 does not actually fixes anything for this issue, but does fix the (imo) most common case where people does not set a layer name.

**Comment by pramsey** [comment]
I think this issue is just maybe more doco needed somewhere?

**Comment by pramsey** [comment]
I've added a few lines of doco about layer source names while closing #135 in 34ffdb87797d5feaf3884482ed9c6e15afafa665
