### ISSUE TITLE
pg_tileserv vs pg_featureserv

### ISSUE THREAD

**Issue by gmonk** [CrunchyData/pg_tileserv#137]
Are tileserv and featureserv always used together ?  When would you use one vs the other ?    I have watched a few of the videos https://www.youtube.com/watch?v=TXPtocZWr78  and its seems to me that both provide the same data minus being able to have more query power using feature server. 

Thanks

**Comment by dr-jts** [comment]
Whether `pg_tileserv` and `pg_featureserv` are used together or independently depends on the use case.  They  are different but complementary.   They do serve the same data, but in different formats.  

* `pg_tileserv` delivers data in MVT format, which is optimized for fast viewing of large datasets.  MVT data is automatically tiled and simplified, which makes it fast to deliver, but sometimes more difficult to query 
* `pg_featureserv` serves data in GeoJSON, which provides full-fidelity access to the raw data (spatial and attributes).  This can make the response data size quite large and therefore less efficient to access large volumes of data.

Differentiating use cases include:
* `pg_tileserv`: 
  * fast display of large datasets
  * easy to subset data based on view area
  * cacheable
  * data package optimized for size
  * requires MVT-capable client
  * some local query capability
* `pg_featureserv`: 
  * data extract, feature editing, feature highlighting 
  * supports single-feature query (= WMS `GetFeatureInfo`)
  * may be required for simpler clients
  * less amenable to caching
  * can be used to load a *small* dataset locally for display and query
  * currently `pg_featureserv` offers a (non-standard) geometry transformation capability (but this could be added to `pg_tileserv` as well.)

**Comment by gmonk** [comment]
Thank you for the detailed response this gives me a better understanding.
