### ISSUE TITLE
Timeout: deadline exceeded on 

### ISSUE THREAD

**Issue by noeltech** [CrunchyData/pg_tileserv#139]
<img width="1678" alt="Screen Shot 2022-05-19 at 8 35 12 AM" src="https://user-images.githubusercontent.com/30190120/169178425-f5a44457-fe90-4925-bee6-415e858aed27.png">

Why most of the time i get this error?
How do i get around it? is it with my database? number of features?

Im using Mapbox GL js 2.0 with react, all in localhost
I haven't change any config in the Pg_tileserv
This is what it looks like in my frontend (i sometimes missing a tile)
<img width="1597" alt="Screen Shot 2022-05-19 at 8 50 26 AM" src="https://user-images.githubusercontent.com/30190120/169179189-61923438-867d-4ff6-aa2c-564909318780.png">

**Comment by pramsey** [comment]
How big is that table? I mean, the query is timing out, so...? Large table no index? Large table and you're rendering all of it into the tiles? (Doesn't look like it from your screen shot.) If it's a small table, I have no clue. You can always copy that SQL out of the debug log and run it manually and use `EXPLAIN` to try to get a handle on where the performance issue is.
