### ISSUE TITLE
countries_name

### ISSUE THREAD

**Issue by btran1315** [CrunchyData/pg_tileserv#140]
Hi.  I am playing with pg_tileserv and it's wonderful but I can't get countries_name function to work properly.  When opening it under Function Layers it only shows the map but not selected countries.  I can, however, download each .pbf files and able to display them into QGIS fine.  I don't know if it's missing a library or configuration.  Everything else works fine like Table Layers.  Thank you in advance.
![countries_name_empty](https://user-images.githubusercontent.com/82381554/170026929-5cb0c157-c128-42aa-a320-4e8d351c5e3b.PNG)
![countries_name](https://user-images.githubusercontent.com/82381554/170026939-77bcdbdb-4ca7-45d9-b419-d44d7d7b030d.PNG)

**Comment by pramsey** [comment]
I'm sorry I'm not seeing this. If you watch the log output while running that might provide a clue.

**Comment by btran1315** [comment]
Thanks for responding but this is all I see.  Is there log somewhere else?

time="2022-05-27T07:08:00-04:00" level=info msg="GET /public.countries_name/0/0/0.pbf?name_prefix=C" method=GET url="/public.countries_name/0/0/0.pbf?name_prefix=C"
time="2022-05-27T07:08:00-04:00" level=info msg="GET /public.countries_name/0/0/0.pbf?name_prefix=C" method=GET url="/public.countries_name/0/0/0.pbf?name_prefix=C"
time="2022-05-27T07:08:00-04:00" level=info msg="GET /public.countries_name/0/0/0.pbf?name_prefix=C" method=GET url="/public.countries_name/0/0/0.pbf?name_prefix=C"

**Comment by pramsey** [comment]
Those look like successful requests so the server is doing its thing. Check the web developer logs in your browser, maybe there's something broken in the client.

**Comment by btran1315** [comment]
I don't see anything there either.  Everything looks fine.  
![ff_tile_loads](https://user-images.githubusercontent.com/82381554/171398826-ae64cf5c-50df-427c-81e2-241b439b1b69.PNG)
![ff_tile_update](https://user-images.githubusercontent.com/82381554/171398845-1220062d-d261-4cc1-a3da-152b80a32894.PNG)
![ff_tile_pbf](https://user-images.githubusercontent.com/82381554/171398855-374f61d9-1219-4dc8-afe5-12962ea7d358.PNG)
![ff_tile_logs](https://user-images.githubusercontent.com/82381554/171398867-abf19ac0-06bc-4810-941d-fd084f97b693.PNG)
