### ISSUE TITLE
The default feature limit per tile is unclear

### ISSUE THREAD

**Issue by jingsam** [CrunchyData/pg_tileserv#143]
As stated in docs, The default feature limit per tile is 50000:

```
limit controls the number of features to write to a tile. The default is 50000.
```
But the code says the default feature limit per tile is 10000:

https://github.com/CrunchyData/pg_tileserv/blob/ed7d54791dc2982a6f1ee54cb7b31f192ab49756/main.go#L81

**Comment by pramsey** [comment]
Could have sworn I fixed that.... done now at 760bdb0
