### ISSUE TITLE
[Feature request]Add static folder for static assets.

### ISSUE THREAD

**Issue by jingsam** [CrunchyData/pg_tileserv#144]
I use pg_tileserv in an air gapped environment. So I tried to download mapbregl,  jquery into assets folder. Then modify `preview-table.html` and `preview-function.html` to reference these files. However it doesn't work. It would be better allow users to specify a static folder to serve static assets like images, libraries, css .etc.

**Comment by pramsey** [comment]
We've resisted serving static content, as we don't want to turn the system into a small web server. Just put the resources on some other static serving system.
