### ISSUE TITLE
Feature Request: _bbox in properties for all features

### ISSUE THREAD

**Issue by reyemtm** [CrunchyData/pg_tileserv#147]
would it be possible to add a _bbox or _bounds field to all returned features inside the feature properties for all layers that are not points? Why do this - because when rendering vector tiles often you do not have access to the whole geometry of a line or polygon - which makes it difficult to enable something like a `zoom-to` feature on a map. If a simple extent was added as a property for all features then this `zoom-to` feature could be implemented. This would be a standout feature from other vector tile generators as far as I know. While the user could add a bounds field on their end - it would be awesome if it just appeared in the tile data. This could be a flagged option, off by default, for example `ADD_EXTENT` then `EXTENT_FIELD_NAME`.

**Comment by pramsey** [comment]
This seems like something that should be in the tile [specification](https://github.com/mapbox/vector-tile-spec/), not adhoc added to a tile generator.
