### ISSUE TITLE
Question : How much memory is suitable?

### ISSUE THREAD

**Issue by gogo-boot** [CrunchyData/pg_tileserv#150]
Hi, 
I like to bring this tile server  on production system. 
I wonder, how much memory allocation is suitable for this tile server?
I have no idea. allocate 2GiB? 4GiB? or as much possible? what can be good enough for nice performance?

**Comment by pramsey** [comment]
It's a fat binary with a memory manager in it, but I would not expect it to have a memory foot print of a lot more than a few hundreb Mb in the extreme.
