### ISSUE TITLE
Provide option for overwriting layer name

### ISSUE THREAD

**Issue by lucasprograms** [CrunchyData/pg_tileserv#151]
By default, the layer name (`name` argument for ST_AsMVT) is the name of the table. Since this information is exposed in the tile, it might be beneficial to use a different layer name.

Enhancement: Provide an option to override the default value with a static string.

If this is accepted as an option I could have a crack at it, although I would be learning Go at the same time :)

There would also be a question about how to handle this for multi-table tiles, as a static string would not work in that case.

**Comment by pramsey** [comment]
For multi-layer tiles it could be a prefix, but I'm uncertain of the value of that. And are you proposing a single layer name to be used for all output? 'default' or something? For a lot of uses that would be simplifying.

**Comment by lucasprograms** [comment]
> And are you proposing a single layer name to be used for all output? 'default' or something?

yes, exactly. Although it could be provided by a query ~pramseyter~ parameter

**Comment by pramsey** [comment]
OK, sounds good.

**Comment by pramsey** [comment]
Crack open a PR when you've got it.
