### ISSUE TITLE
Error downloading binaries from website

### ISSUE THREAD

**Issue by rwegener2** [CrunchyData/pg_tileserv#152]
Hi 👋🏻 

I am really excited to come across this software, but I'm having a hard time downloading it. When I click on the "OSX" link under "A. Download Binaries" of the [Installation page](https://access.crunchydata.com/documentation/pg_tileserv/latest/installation/), I get.

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>pg_tileserv_latest_osx.zip</Key>
<RequestId>G53XAJMJDRBKB2C0</RequestId>
<HostId>/tIqXIt/JkpL96TduNEAcxlw6eTXMxapzOUX3l+jQuREJyWpSpiIlNgSx2st06gsOObEAytzSCc=</HostId>
</Error>
```

The url behind that link seems to be https://postgisftw.s3.amazonaws.com/pg_tileserv_latest_osx.zip.

Is that something I am doing wrong? Thank you!

**Comment by pramsey** [comment]
Ah, the links are out of date on that page... the README has the right one, here you go: https://postgisftw.s3.amazonaws.com/pg_tileserv_latest_macos.zip

**Comment by rwegener2** [comment]
Thank you so much!
