### ISSUE TITLE
OSX Download link in documentation broken

### ISSUE THREAD

**Issue by brianbancroft** [CrunchyData/pg_tileserv#154]
When accessing the downloads through the documentation (https://access.crunchydata.com/documentation/pg_tileserv/1.0.8/installation/), the OSX link is broken. 

https://postgisftw.s3.amazonaws.com/pg_tileserv_latest_osx.zip

Download links for Linux, and Windows still perform as advertised.

**Comment by brianbancroft** [comment]
Looking deeper into this, it appears that the documents have been updated in the codebase, and it's all just pending deployment. 

https://github.com/CrunchyData/pg_tileserv/commit/c82bd974be6b36ff7a963bafa7be6921204ad09d

**Comment by pramsey** [comment]
Correct, I'm hoping hte 1.0.9 builtout will fix this.
