### ISSUE TITLE
Assets refers to localhost:9000 when proxy is used

### ISSUE THREAD

**Issue by romain974** [CrunchyData/pg_tileserv#158]
I have a nodejs proxy that redirect requests to internal pg_tileserv.
localhost:3000/tiles => localhost:9000
Every thing works perfectly, except the html links  => ex:  index.html   links point to localhost:9000.

I figure out to modify html to do what I want (replace localhost:9000 by '/tiles/'), but if there's a better solution, let me know.
The same thing happen with pg_featureserv, and I hav'nt found a solution yet.

**Comment by romain974** [comment]
Will give a try, but I've already played around with those 2 parameters. I'll try again. Thanks for your response.

**Comment by brunorpinho** [comment]
If you set the `UrlBase` everything works as expected and is correctly "proxied", except the table links in the html page. Those are: 
**/<table_name>.json** 
but they should be
 **<BaseUrl>/<table_name>.json**

**Comment by rhewy** [comment]
Anyway to fix this?

I have nginx installed locally with pg_tileserv in a container and pg_featureserv in another container

```
        location /pgfs/ {
             proxy_pass http://localhost:9000/ ;
        }
        location /pgts/ {
             proxy_pass http://localhost:7800/ ;
        }

```
My .env file used for launching the container has the line below:
```
TS_URLBASE=https://vm103.athena.bcit.ca/pgts/
```
The web interface thinks everything maps to
https://vm103.athena.bcit.ca/
Not
https://vm103.athena.bcit.ca/pgts/

If I manually add **/pgts/** to the url it is found. But all of the json such has index.json is off, just https://vm103.athena.bcit.ca/

If I add TS_BASEPATH environment variable to the file as shown below:
```
TS_BASEPATH=/pgts/
```
Then I can get the the main page but then the address are off again. If I manually edit them buy adding prefix
 
https://vm103.athena.bcit.ca/pgts/pgts/ then I can access them again.

Always seem to be off by a little bit.
