### ISSUE TITLE
Property disappear if has null value

### ISSUE THREAD

**Issue by romain974** [CrunchyData/pg_tileserv#159]
If a database field value is null, the corresponding property seems to be absent of the tile.
(If I set an empty string, every thing works as excepted)
Is it the normal behaviour or a bug ?
This can be annoying for certain applications.

**Comment by pramsey** [comment]
Hard call. It's kind of normal for the tile format, which is defined not in terms of a fixed "set of columns" but rather a completely optional "collection of tags". That said, our tiles are being generated from a system that does have a fixed set of columns. I have a feeling this might be happening deep in the PostGIS ST_AsMVT function, in which case, yeah, that's just the behaviour you're going to get.

**Comment by pramsey** [comment]
Yeah, confirmed this is not a behaviour of pg_tileserv, it's actually a behaviour of ST_AsMVT in PostGIS. You can workaround right now with a custom function to generate your tiles, that wraps the columns of concern in a Coalesce(col, '') to turn the NULL into ''. It's possible we could optionally do the same thing, at the price of a somewhat more ugly SQL generation. Will have to look closer yet.
