### ISSUE TITLE
Disappearing polygons at specific zoom levels.

### ISSUE THREAD

**Issue by reyemtm** [CrunchyData/pg_tileserv#160]
This is a normal polygon feature yet at certain zoom levels it disappears. I will attempt to recreate it as a test case with the data again and provide the raw data. Any ideas or suggestions would be helpful.

Affected zoom levels - 5,6

**Version**

POSTGIS="3.0.3 3.0.3" [EXTENSION] PGSQL="130" GEOS="3.5.0-CAPI-1.9.0 4392" PROJ="Rel. 6.0.0, March 1st, 2019" LIBXML="2.9.4" LIBJSON="0.15" LIBPROTOBUF="1.4.0"

![missing](https://user-images.githubusercontent.com/6398929/194358494-b0252b13-a05d-4ad6-b633-07a8a9b83a50.gif)

**Data**
[GeoPackage](https://tileserv.nyc3.digitaloceanspaces.com/public/_tmp_msa_outlines.gpkg)

**Comment by pramsey** [comment]
Looks like it's failing to render at a particular zoom level so you'll have to both get the data and get an idea of what zoom level this is happening at. Maybe it's foiling the PostGIS clipping routines. Will also need your postgis_full_version()

**Comment by reyemtm** [comment]
I think it has something to do with number of vertices I in the tile created by `ST_AsMVT()`. If I run the geom through `ST_Simplify()` I dont get the error - 
```ST_AsMVTGeom(ST_Simplify(t.geom,1), bounds.geom) AS geom```

**Comment by reyemtm** [comment]
If I turn down the simplification the error returns.

**Comment by pramsey** [comment]
Simplifying also changes the shape of the object. It could be a lot of things still.

**Comment by reyemtm** [comment]
```
POSTGIS="3.0.3 3.0.3" [EXTENSION] PGSQL="130" GEOS="3.5.0-CAPI-1.9.0 4392" PROJ="Rel. 6.0.0, March 1st, 2019" LIBXML="2.9.4" LIBJSON="0.15" LIBPROTOBUF="1.4.0"
```

**Comment by reyemtm** [comment]
Looks to be a postgis issue that has since been fixed - tested with a new version and the bug does not show up. Once I confirm which version works I will close the issue.
