### ISSUE TITLE
Does pg_tileserv support unix socket 

### ISSUE THREAD

**Issue by chinchillaLiao** [CrunchyData/pg_tileserv#161]
I'm trying to deploy pg_tileserv on Google Cloud Run, which can only connect to Cloud SQL (PostreSQL) with Unix Socket, is there anyway to add socket informaion in DATABASE_URL? For example:
postgresql://<user_name>:<pass_word>@/<DB>?unix_sock=/cloudsql/<cloud_sql_connect_name>/.s.PGSQL.5432

**Comment by pramsey** [comment]
I've not found any.
