### ISSUE TITLE
Return "geom" colunm in the properties of vector tile

### ISSUE THREAD

**Issue by digoburigo** [CrunchyData/pg_tileserv#162]
Hello, i want to know if it's possible to return the geom column, possibly WKB string, inside the vector tile properties

**Comment by pramsey** [comment]
Kind of defeats the purpose of having a compact binary representation of the geometry in the tile. If you want direct access to the original feature coordinates use pg_featureserv instead (or use both, use tileserv for rendering, and do an on-demand pull of needed features from featureserv as required).
