### ISSUE TITLE
Sampling of points at lower zoom.

### ISSUE THREAD

**Issue by jingsam** [CrunchyData/pg_tileserv#166]
I have millions of points to be visulized in map. At lower zoom such as zoom 0, there will be millions of points in one tile. Although I can use `limit` parameter to limit the max number of features in one tile, but it does not preserve the spatial pattern of points because it just choose a set of points based on the order of rows in database table.

So I guess I could randomly choose a set of points using `filter` as follows:

```
http://localhost/pg_tileserv/public.poi/0/0/0.pbf?limit=10000&filter=random()<0.2
``` 

However, it seems `filter` only support properties or literal value, not support functions.

**Comment by pramsey** [comment]
Or a view.
