### ISSUE TITLE
Opt out index/preview pages and/or json metadataendpoints

### ISSUE THREAD

**Issue by bjornharrtell** [CrunchyData/pg_tileserv#167]
Might want to not have the service discoverable or have to consider proxying at all.

**Comment by pramsey** [comment]
that would still leave the json endpoints, presumably, so still discoverable in some sense? just more of a cleanliness thing (not exposing the html stuff?)

**Comment by bjornharrtell** [comment]
Hmm I had in mind to also not expose the json endpoints as they are also affected by references that are wrong without rewriting.

**Comment by pramsey** [comment]
So really just the tile endpoint?

**Comment by eldang** [comment]
I believe this is resolved by #196 .  Sorry I didn't reference this issue there - I had missed that there was an existing issue about that.
