### ISSUE TITLE
why cant i query tiles ?

### ISSUE THREAD

**Issue by felixxguilherme** [CrunchyData/pg_tileserv#168]
im trying to query tiles, and nothing works for any reason.
i have some tables and would like to filter the data by year but i can't in any way

im trying
http://localhost:7800/public.dados_e_geom_veg_municipios/{z}/{x}/{y}.pbf?properties=cd_mun,ano,b2&filter=ano=2016
http://localhost:7800/public.dados_e_geom_veg_municipios/{z}/{x}/{y}.pbf?properties=cd_mun,ano,b2&filter = ano = 2016
http://localhost:7800/public.dados_e_geom_veg_municipios/{z}/{x}/{y}.pbf?properties=cd_mun,ano,b2&ano = 2016

i try as in the example on documentation :

http://localhost:7800/public.dados_e_geom_veg_municipios/{z}/{x}/{y}.pbf?limit=100000&properties=cd_mun,nm_mun

and stills returning all properties

nothing works, can anybody helps ?

**Comment by robe2** [comment]
@felixxguilherme  Where are you trying this?  Those above urls are meant to be put in a mapping template, not to be run directly in an address bar.  If that is what you are doing, that is probably your problem.

The {z} {x} and {y} are placeholders which are replaced by the javascript mapping api with positions the user is zoomed into and it makes a call for each rectangle on the maps.
