### ISSUE TITLE
Point is not shown when zoom > 1 and longitude is = -90

### ISSUE THREAD

**Issue by amrabouelenin** [CrunchyData/pg_tileserv#183]
We had a pg_tilserv setup with Mapbox using the Function layer method. 
it works pretty well with displaying all dots in the map, except with one point at longitude=-90 and lattitude=35.8, The point appears in zoom level =1, but when zoom in more it disappears from the map. The SQL function query in the backend returns the geometry of that station, but the point is still not shown up on the map. I have to zoom out back to level 1 to appear. 

Is it a problem with pg_tileserv not handling such a unique case? is there a special configuration for that?

The SQL function is below for reference, however, it is working absolutely fine

`
CREATE OR REPLACE FUNCTION tileserv.func_name(
	z integer,
	x integer,
	y integer)
    RETURNS bytea
    LANGUAGE 'plpgsql'
    COST 100
    STABLE SECURITY DEFINER PARALLEL SAFE 
    SET search_path=public
AS $BODY$

DECLARE 
    worldMercMax FLOAT := 20037508.3427892;
    worldMercMin FLOAT := -1 * worldMercMax;
    worldMercSize FLOAT := worldMercMax - worldMercMin;
    worldTileSize FLOAT := 2^z;
    tileMercSize FLOAT := worldMercSize / worldTileSize;
    xmin FLOAT:= worldMercMin + tileMercSize * x  ;
    xmax FLOAT := worldMercMin + tileMercSize * (x + 1);
    ymin FLOAT := worldMercMax - tileMercSize * (y + 1);
    ymax FLOAT := worldMercMax - tileMercSize * y;
BEGIN

RETURN (SELECT ST_AsMVT(tile, 'sys-func_name')                                       
   FROM (select station,country_id,                                                      
       ST_AsMVTGeom(geom, ST_Makebox2d(ST_SetSrid(ST_MakePoint(xmin,ymin),3857),                                            
       ST_SetSrid(ST_MakePoint(xmax,ymax),3857)), 4096, 256, false) AS geom
       FROM (**INNER QUERY**) AS SEL                              
   WHERE ST_Intersects(geom, (SELECT ST_MakeEnvelope(xmin, ymin, xmax, ymax, 3857)))
   ) AS tile);

END 
`
I am using mapbox and here is the function in js

`url = `${TILES}/tileserv.${functionName}/{z}/{x}/{y}.pbf`;
    map.addLayer({
      id: layerName,
      type: "circle",
      source: {
        type: "vector",
        tiles: [url],
        minzoom: 0,
        maxzoom: 16
      },
      "source-layer": layerName,
    });
`

**Comment by pramsey** [comment]
Have you taken https://github.com/mapbox/vt2geojson and decoded the tile you think should be holding the point? Just to make sure the final tile that goes to mapbox actually has the point. The only special about longitude 90 is that it's right on a tile boundary, so *maybe* there's something about the mapbox rendering that is causing it to disappear?
