### ISSUE TITLE
How to get labels along with geometries in protobuf tiles rendered using Leaflet.vectorGrid?

### ISSUE THREAD

**Issue by ashuvssut** [CrunchyData/pg_tileserv#184]
Its not a bug report but a question

I am using pg_tileserv to get .pbf. 
I receive tiles in which there are only roads. Those roads must have been generated by the `geom` column from the table. But I also want to labels along the road's geometry **as a separate layer**. I have a `name` and a `ref` column in which you can see that there are a labels. I want to show them along the road's geometry.

> I do not want these labels as **embedded** along with the roads geometry, it should be **separate layer** (thus a separate call the pg_tileserv)

How can I acheive this?

![image](https://github.com/CrunchyData/pg_tileserv/assets/60546840/cb675216-a71d-4448-897c-bceec2f8530e)

Here's the JS code that i use in the frontend to add the `roads` layer in my map. I use `Leaflet.vectorGrid`
```js
    const pbfFilename = `public.${selectedBundle}_${Layer}`;

    const vectorUrl = `${TILE_SERVER_URL}/${pbfFilename}` + "/{z}/{x}/{y}.pbf";
    const vectorTileStyling = {};

    vectorTileStyling[pbfFilename] = stylesObj[Layer] || getDefaultStyles();
    const tileLayer = L.vectorGrid.protobuf(vectorUrl, {
      rendererFactory: L.canvas.tile,
      name: layerId,
      vectorTileLayerStyles: vectorTileStyling,
      className: layerId,
    });
    tileLayer.addTo(map);
```

**Comment by ashuvssut** [comment]
We used pg fetureserv to implement this labeling

**Comment by jos3ma** [comment]
Hi @ashuvssut ! I need to do the exact same thing. Can you give me any clues about how you managed to implement those labels? Thanks in advance!

**Comment by ashuvssut** [comment]
Sorry, in my Previous company I just did the Frontend work for implementing those maps. Regarding using pg_featureserve, the backend team added few columns for labelling data. I created separate Layers to show that "label layer". Make sure to have a "zoom level" column to0. In different zoom level you will show only the few labels that match that zoom level. Maps are slower when there's too many labels to render in that "label layer"

**Comment by jos3ma** [comment]
I've been able to add the vector tiles using pg_tileserv, but I can't find a way to add tags to them, and I can't find a way to add tags using pg_featureserv either. I've followed some examples, but I can't get them to work. Anyway, I'll keep investigating and testing. If you have a link to a plugin or an example that's been helpful in learning this, please share it with me. Thank you so much for your help @ashuvssut . Best regards!

**Comment by ashuvssut** [comment]
Really sorry man,, I worked on that about two years ago and no longer have access to the old codebase, so I’m not sure which React-Leaflet plugin I used at the time.
