### ISSUE TITLE
docker pg_tileserv:20231121 `GLIBC_2.34' not found 

### ISSUE THREAD

**Issue by ImreSamu** [CrunchyData/pg_tileserv#198]
The latest version of Docker image (  `pramsey/pg_tileserv:20231121 ` )  - it seems like it's not working : 

```bash
$ docker run -it --rm  pramsey/pg_tileserv:20231121 pg_tileserv --debug
/app/pg_tileserv: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /app/pg_tileserv)
/app/pg_tileserv: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /app/pg_tileserv)
```

EDIT1:
A temporary solution: You can use an older version: `pramsey/pg_tileserv:20231005`
For other previous versions, please visit: https://hub.docker.com/r/pramsey/pg_tileserv/tags

EDIT2:
If you are also experiencing this issue, please simply use the "👍" emoji without adding a comment..

**Comment by kdiaz1105** [comment]
I am facing the same issue. 
```
2023-11-28 05:56:29 /app/pg_tileserv: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /app/pg_tileserv)
2023-11-28 05:56:29 /app/pg_tileserv: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /app/pg_tileserv)
```

**Comment by niekvanruler** [comment]
any progress on this issue?

**Comment by asindl** [comment]
I have the same problem...

**Comment by ImreSamu** [comment]
@asindl 

> I have the same problem...

A temporary solution: You can use an older version:  `pramsey/pg_tileserv:20231005`

For other previous versions, please visit:  https://hub.docker.com/r/pramsey/pg_tileserv/tags

**Comment by ntatko** [comment]
Me, too!

**Comment by immocalcul** [comment]
same trouble here my version is 2.36

**Comment by pramsey** [comment]
Should be building out working (?) images again in latest-amd64 and latest-arm64.

**Comment by ImreSamu** [comment]
Thank you for the correction!
I have tested the `pramsey/pg_tileserv:20240123` Docker image, and everything is fine with it!


I have one (non-critical) comment to make, which is that currently, the "latest" and "latest-amd64" versions differ. 
https://hub.docker.com/r/pramsey/pg_tileserv/tags

- `pramsey/pg_tileserv:latest`  Last pushed 5 days ago
- `pramsey/pg_tileserv:latest-amd64` Last pushed an hour ago

If it could be arranged for the two images to match, it would better preserve compatibility.

**Comment by pramsey** [comment]
I think I just need to delete the 'latest' tag. It will henceforth be a 'latest-amd64' and 'latest-arm64' (coming shortly)

**Comment by pramsey** [comment]
Oh and thanks to @crunchyheath the images are now 15Mb instead of 75Mb, very nice

**Comment by ImreSamu** [comment]
> I think I just need to delete the 'latest' tag. It will henceforth be a 'latest-amd64' and 'latest-arm64' (coming shortly)

Note:
The default Docker tag is now "latest", so the documentation should be updated accordingly.

```
$ docker pull pramsey/pg_tileserv

Using default tag: latest
Error response from daemon: manifest for pramsey/pg_tileserv:latest not found: manifest unknown: manifest unknown
```

1.)

On the Docker Hub page https://hub.docker.com/r/pramsey/pg_tileserv , 
the "Overview" section still show the "Docker Pull Command:"  `docker pull pramsey/pg_tileserv` , 
and in the "Overview"  example, it uses 
`docker run -dt -e DATABASE_URL=postgresql://user:pass@host/dbname -p 7800:7800 pramsey/pg_tileserv:latest`


2.)

Additionally, in the documentation 
https://github.com/CrunchyData/pg_tileserv/blob/master/hugo/content/installation/_index.md , 
the Docker example also appears without a tag, and since there is no longer a "latest" tag, 
this will not work and should be corrected.
* now: `docker run -e DATABASE_URL=postgres://user:pass@host/dbname -p 7800:7800 pramsey/pg_tileserv`
* proposed `docker run -e DATABASE_URL=postgres://user:pass@host/dbname -p 7800:7800 pramsey/pg_tileserv:latest-amd64`

**Comment by pramsey** [comment]
PR? 🙏

**Comment by crunchyheath** [comment]
We could leave the latest tag and make it into a manifest so that it will pull the appropriate image based upon the architecture you are currently on.  Just a thought, and it may make it so you don't need to PR this change.
