### ISSUE TITLE
# in the connection string

### ISSUE THREAD

**Issue by netgis** [CrunchyData/pg_tileserv#217]
if I start the password for pg_tileserv with a hash, pg_tileserv does not work, e.g.
DbConnection = “postgresql://postgres:#QRxyz@localhost:5015/mydb”
I can fix the problem by using the percent-encoded equivalent for # -> %23, but it would be good if the string allowed the character.

**Comment by jamesscottbrown** [comment]
There is an equivalent issue in CrunchyData/pg_featureserv: https://github.com/CrunchyData/pg_featureserv/issues/150

The reason for not being able to use the `#` character is that the connection string is parsed as a URL.
