### ISSUE TITLE
pg_tileserv CQL filter doesn't work correctly for LIKE and ILIKE with wildcard

### ISSUE THREAD

**Issue by andrewlee8247** [CrunchyData/pg_tileserv#218]
When I add a wildcard for LIKE or ILIKE using cql it doesn't seem to work and I get all the vector data. This is an example url:
http://localhost:7800/tenant_a.properties{z}/{x}/{y}.pbf?filter=event%20ILIKE%20%27%25dixie%20fire%25%27

When I don't use a wildcard it works. This is an example url:
http://localhost:7800/tenant_a.properties{z}/{x}/{y}.pbf?filter=event%20ILIKE%20%27dixie%20fire%27

I would really like for this to work. Am I doing something wrong? I definitely do not want to create a function to support this.

This is how it should be like:
![Screenshot 2024-08-28 at 2 15 20 PM](https://github.com/user-attachments/assets/0264829b-b5a8-45cf-917d-9edc1fc78cd3)

But I get this with wildcard:
![Screenshot 2024-08-28 at 2 14 40 PM](https://github.com/user-attachments/assets/7b58f09f-ec89-4afb-a8c1-2071bf0bf8fe)

**Comment by dr-jts** [comment]
This looks like a bug in the `pg_tileserv` CQL transpiler, where the leading `%` is converted to a `*` character, producing the following SQL (snippet):
```
AND \"name\" ILIKE '*n%'
```
Interestingly this works in `pg_featureserv`:
```
WHERE (\"name\" ILIKE '%an%')
```

**Comment by dr-jts** [comment]
If you can avoid using leading wildcard characters it should work.  Otherwise feel free to create a patch, or wait for a fix.

**Comment by dr-jts** [comment]
Whoops, my bad - the URL I was using for testing didn't have the right URL code for `%`.  When I fix that it works as expected:
```
http://localhost:7800/ne.admin_0_countries.html?filter=name%20ILIKE%20%27%25an%25%27#1.56/23.7/-45.8
```
produces SQL containing:
```
AND \"name\" ILIKE '%an%'
```

Is it possible you are using an older version of `pg_tileserv`?

**Comment by andrewlee8247** [comment]
I am using docker image with tag: 
20240614 or pramsey/pg_tileserv:20240614

**Comment by dr-jts** [comment]
Seems pretty recent.

Can you run `pg_tileserv -d` and see what SQL is emitted?

**Comment by andrewlee8247** [comment]
This is what I get from the logs:
`INFO[12935] GET /tenant_a.properties/10/843/606.pbf?filter=event%20ILIKE%20%27dixie%20fire%27  method=GET url="/tenant_a.combined_policy_view/10/843/606.pbf?filter=event%20ILIKE%20%27mariginiup%20fire%27"`

**Comment by dr-jts** [comment]
That's the HTTP{ query string.  You can see the generated SQL by running `pg_tileserv` with the `-d` option.

**Comment by andrewlee8247** [comment]
Got it. Yeah so without the wildcard the query looks right:
```INFO[0378] GET /tenant_a.properties/1/0/1.pbf?filter=event%20ILIKE%20%dixie%20fire%27  method=GET url="/tenant_a.properties/1/0/1.pbf?filter=event%20ILIKE%20%dixie%20fire%27"
TRAC[0378] requestTile: 1/0/1.pbf                        event=request key=1/0/1.pbf topic=tile
DEBU[0378] 
	SELECT ST_AsMVT(mvtgeom, 'tenant_a.properties', 4096, 'geom') FROM (
		SELECT ST_AsMVTGeom(
			ST_Transform(ST_Force2D(t."geom"), 3857),
			bounds.geom_clip,
			4096,
			256
		  ) AS "geom"
		  
		  , "event"
		  
		FROM "tenant_a"."properties" t, (
			SELECT ST_MakeEnvelope(-2.00375083427892e+07, -2.00375083427892e+07, 0, 0, 3857)  AS geom_clip,
					ST_MakeEnvelope(-2.00375083427892e+07, -2.00375083427892e+07, 1.252344271424325e+06, 1.252344271424325e+06, 3857) AS geom_query
			) bounds
		WHERE ST_Intersects(t."geom",
							ST_Transform(bounds.geom_query, 4326))
			AND "event" ILIKE 'dixie fire'
		LIMIT 50000
	) mvtgeom```

With the wildcard it doesn't event apply the filter in WHERE clause:
```INFO[0544] GET /tenant_a.properties/3/7/5.pbf?filter=event%20ILIKE%20%27%dixie%20fire%%27  method=GET url="/tenant_a.properties/3/7/5.pbf?filter=event%20ILIKE%20%27%dixie%20fire%%27"
TRAC[0544] requestTile: 3/7/5.pbf                        event=request key=3/7/5.pbf topic=tile
DEBU[0544] 
	SELECT ST_AsMVT(mvtgeom, 'tenant_a.properties', 4096, 'geom') FROM (
		SELECT ST_AsMVTGeom(
			ST_Transform(ST_Force2D(t."geom"), 3857),
			bounds.geom_clip,
			4096,
			256
		  ) AS "geom"
		  
		  , "event"
		  
		FROM "tenant_a"."properties" t, (
			SELECT ST_MakeEnvelope(1.5028131257091898e+07, -1.00187541713946e+07, 2.00375083427892e+07, -5.0093770856973e+06, 3857)  AS geom_clip,
					ST_MakeEnvelope(1.4715045189235818e+07, -1.033184023925068e+07, 2.00375083427892e+07, -4.696291017841218e+06, 3857) AS geom_query
			) bounds
		WHERE ST_Intersects(t."geom",
							ST_Transform(bounds.geom_query, 4326))
			
		LIMIT 50000
	) mvtgeom```

Strange because the URL request looks fine.

**Comment by dr-jts** [comment]
> Strange because the URL request looks fine.

The request seems to have a double `%%`  after `fire`?
```
/tenant_a.properties/3/7/5.pbf?filter=event%20ILIKE%20%27%dixie%20fire%%27
```

**Comment by andrewlee8247** [comment]
That's the wildcard. I am sending it with %25 as indicated in the docs but in the request it has it as `% ` and the `%27` represents a single quote. Again the string I am sending is in this format:
http://localhost:7800/tenant_a.properties{z}/{x}/{y}.pbf?filter=event%20ILIKE%20%27%25dixie%20fire%25%27

**Comment by dr-jts** [comment]
In my `pg_tileserv` log I see the following:
```
INFO[5620] GET /ne.admin_0_countries/2/3/1.pbf?filter=name+ILIKE+%27%25an%25%27  method=GET url="/ne.admin_0_countries/2/3/1.pbf?filter=name+ILIKE+%27%25an%25%27"
```
So in my environment the URL encoding is preserved going into the service.  I'm not sure why yours decodes the `%25` to `%`.  But seems like a possible issue.

**Comment by andrewlee8247** [comment]
Strange and frustrating. I can try rebuilding the container from cloning repository and see if that fixes the issue.

**Comment by andrewlee8247** [comment]
I was able to get it to work by adding and extra 25 `%2525`. So the URL is like this
http://localhost:7800/tenant_a.properties{z}/{x}/{y}.pbf?filter=event%20ILIKE%20%27%2525dixie%20fire%2525%27
