### ISSUE TITLE
Query: Would it be too difficult to port pg_tileserv to duckDB?

### ISSUE THREAD

**Issue by javierurien** [CrunchyData/pg_tileserv#221]
Hello maintainers,
  I was wondering what would be the crazyness level of wanting to add DuckDB as a backend for pg_tileserv?

Regards.

**Comment by pramsey** [comment]
pg tileserv is for pg. You're welcome to fork, or just to copy the bits you like, if you do a Duck-specific project.

**Comment by pramsey** [comment]
At a basic level no more so than writing tileserv in the first place, which started from a 40 line python script. Your immediate problem is that duckDB doesn't have an ST_AsMVT function, so you'd be writing that from scratch in your server. Oh, regards the craziness level, seems pretty. high to me, but I'm sure you have your reasons.

**Comment by javierurien** [comment]
Thank you for the quick replies. It seems that there is a duckdb developer working on ST_AsMVT, so that might lower the work. Fingers crossed!

Thanks again!
