### ISSUE TITLE
Which Geometry types can produce tiles?

### ISSUE THREAD

**Issue by SeanBatt** [CrunchyData/pg_tileserv#32]
I haven't seen documentation anywhere about the geometry types that pg_tileserv can work with and it might save others time to have that described somewhere.

For example, Point is fine. Polygon is, too. But PolygonZ and Multipoligon silently fail. 

The logging, even at --debug level, don't give enough detail to understand what is happening (or not) with requests that produce nothing. I wonder if that can be improved? (While I'm happy to jump into the source, I have to teach myself go as I do so, the only change I've been brave enough to make so far has been to update the version from 0.1.)

The list of available sources pg_tileserv shows in index.html/json gives no indication that tiles can't be retrieved, though I would think the type of geometry is available when that list is produced.

**Comment by stephenhillier** [comment]
I'm not the maintainer, but I think part of this might just be a limitation of the preview map. I made a quick PR (#34 ) that adds paint types for 3D geometries like PolygonZ and LineStringZ.  MultiPolygons are already working for me; I can try to help if you post an example.

**Comment by pramsey** [comment]
Did the PR make things better for your, @SeanBatt ?

**Comment by pramsey** [comment]
Also note that in order for a table to be registered as a tile layer it needs to have a geometry column that expresses both its **type** and its **srid** so the system can reproject it to the web mercator system preferred by tiles.
