### ISSUE TITLE
Layer points not showing up

### ISSUE THREAD

**Issue by lucadegasperi** [CrunchyData/pg_tileserv#33]
I have a table which I managed to make appear in pg_tileserv. Now when I try to explore the layer I can't see any points despite them being there in the table. I ran `SELECT UpdateGeometrySRID('helipads','the_geom',4326);` to make the table appear in the initial pg_tileserv screen but can't display the points yet. What am I doing wrong?

```sql
DROP TABLE IF EXISTS "public"."helipads";
-- This script only contains the table creation statements and does not fully represent the table in the database. It's still missing: indices, triggers. Do not use it as a backup.

-- Sequence and defined type
CREATE SEQUENCE IF NOT EXISTS helipads_id_seq;

-- Table Definition
CREATE TABLE "public"."helipads" (
    "id" int4 NOT NULL DEFAULT nextval('helipads_id_seq'::regclass),
    "the_geom" geometry NOT NULL,
    "name" varchar(255),
    "type" varchar(255),
    "altitude" varchar(255),
    "dimensions" varchar(255),
    "floor" varchar(255),
    "night_use" bool NOT NULL,
    "manager_phone" varchar(255),
    "link" varchar(255),
    "created_at" timestamp(0),
    "updated_at" timestamp(0),
    PRIMARY KEY ("id")
);
```

```sql
INSERT INTO "public"."helipads" ("id", "the_geom", "name", "type", "altitude", "dimensions", "floor", "night_use", "manager_phone", "link", "created_at", "updated_at") VALUES
('1', 'SRID=4326;POINT(12.165278 46.763889)', 'COLLI IN CASIES', 'avio', '1200', '400x20', 'erbosa', 'f', '340 5897933', 'https://moduliweb.enac.gov.it/Applicazioni/avioeli/Avio_04.asp?selaeroporto=49', '2020-02-04 19:34:55', '2020-02-04 19:34:55');
```

**Comment by stephenhillier** [comment]
If you change the column's type to `Geometry(Point, 4326)` in your table they should show up. I believe the preview map checks the geometry column's type to decide whether to draw markers for points, or fill polygons etc.

**Comment by lucadegasperi** [comment]
Thanks @stephenhillier does this mean it's only the preview that isn't showing the point or the tile isn't generated at all?

**Comment by stephenhillier** [comment]
I did a quick test using your table and it looks like it does generate the tiles with the sample point-  it just doesn't display on the preview map.

**Comment by lucadegasperi** [comment]
Thank you, I though I was doing something totally wrong on my side, but this gives me hope I won't have to change all the DB structure to be generating the tiles.

**Comment by pramsey** [comment]
I don't think it will generate tiles, because it won't register as a layer, because it doesn't have an SRID registered in the metadata... without the SRID, the system cannot know how to reproject the points into web mercator for use in the tiles.
```sql
alter table helipads alter column the_geom type Geometry(Point, 4326);
```
