### ISSUE TITLE
Optional Redis Cache Configuration

### ISSUE THREAD

**Issue by jtbaker** [CrunchyData/pg_tileserv#38]
Would it be within in scope of this project to have an optional environment variable configured Redis cache in front of the database to get/set frequently requested tile values from?

I've been looking for a Golang project to work with and would be happy to start piecing together a PR with ideas if it's something that the team felt would be useful and in scope of the project.

Thanks for the work on this - I think it's a much cleaner solution than the one we're currently using in my org (Dynamic SQL).

**Comment by pramsey** [comment]
Is there a reason that using something more decoupled, like a reverse caching proxy or even a CDN wouldn't meet your needs? Squid? Nginx with a reverse proxy? Varnish?

**Comment by jtbaker** [comment]
I hadn't thought of that. I do use NGINX for reverse proxying, but hadn't explored its caching functionality, which I'll dig into now.

Thanks for the suggestion, and closing out the issue (looking forward to the upcoming "discussion" feature for this sort of thing).

**Comment by pramsey** [comment]
I'd love to hear your experience with this approach. I **think** it's a reasonable approach, but I'd love to hear real-world stories of benefits/drawbacks. 

The only operational drawback I can see is that an externally managed cache is hard to link up to a signal from the database when changes in a table invalidate portions of the cache. In an ideal world, insert/update/delete can invalidate the relevant tiles in a cache, but that definitely requires communication between the database and the tile cache.

**Comment by jtbaker** [comment]
Thinking about it, it seems like having a frequent enough cache invalidation (maybe 1-5 minutes?) should generally address that issue, per the [proxy_cache_valid](https://docs.nginx.com/nginx/admin-guide/content-cache/content-caching/) NGINX directive. I guess it depends on how concurrent you expect your data to be though.

**Comment by pramsey** [comment]
Yeah, if you're caching just for load mitigation in a high usage scenario, the global expiration time on the cache will do the trick fine. 

If you're caching because tile generation is slow enough to be noticeable, and you have relatively low usage, then you want your cache to persist until it's actually invalidated by data change.

So many use cases! 😄

**Comment by dBitech** [comment]
there is a NGINX api (
https://docs.nginx.com/nginx/admin-guide/content-cache/content-caching/#purge_request
)
to purge objects from cache.  couple it with a database trigger, and bob's
your uncle.
