### ISSUE TITLE
CORS errors with wikimedia hosted OSM tiles 

### ISSUE THREAD

**Issue by s8mathur** [CrunchyData/pg_tileserv#41]
First off, thanks for the wonderful project! 

The preview HTML pages from tip are pages are unable to load the base map tiles from the default https://maps.wikimedia.org/osm-intl/*  base path due to CORS errors

`[Error] Failed to load resource: Origin https://myserver.com is not allowed by Access-Control-Allow-Origin. (58.png, line 0)  https://maps.wikimedia.org/osm-intl/7/91/58.png)
`

Please use some other tile server for the basemap, or allow Mapbox-style "bring your own API key" base map? 

Also noticed other projects complaining [about wikimedia.org CORS errors in 2020](https://www.traccar.org/forums/topic/cors-policy-problem-when-fetching-images-from-wikipedia-for-map/)

**Comment by pramsey** [comment]
Thanks. It "works for me" using the defaults. What's different about your setup? Browser? The fact that you've set your host name to myserver.com?

**Comment by s8mathur** [comment]
Latest Safari. Also using pg_tileserv behind a Caddyserver proxy configuration with good TLS configuration. I will close this for now, since I have already plugged in the Mapbox base map in my preview*.html. Will consider a PR later if the problem recurs in fresh installs. 
PS: I hope the Wikimedia servers aren't CORS allowing US and Europe IPs, and CORS-denying everyone else.
