### ISSUE TITLE
Materialized views 

### ISSUE THREAD

**Issue by s8mathur** [CrunchyData/pg_tileserv#44]
Hello, 

Is there a way to make `pg_tileserv` work with materialized views?  Even if I call `SetSRID(, 4326)` on the point column while creating the view, the server doesn't make it visible. 

FWIW, a modified query from the README with the `'m'` `relkind` added does not show me the materialized view either. 

```sql
SELECT
    nspname AS SCHEMA,
    relname AS TABLE,
    attname AS geometry_column,
    postgis_typmod_srid (atttypmod) AS srid,
    postgis_typmod_type (atttypmod) AS geometry_type
FROM
    pg_class c
    JOIN pg_namespace n ON (c.relnamespace = n.oid)
    JOIN pg_attribute a ON (a.attrelid = c.oid)
    JOIN pg_type t ON (a.atttypid = t.oid)
WHERE
    relkind IN('r', 'v', 'm') ---- Added the 'm' relationship
    AND typname = 'geometry'
    AND postgis_typmod_srid (atttypmod) != 0;
```

Thanks

**Comment by pramsey** [comment]
Probably multiple things you need to do:
* update the relkind, as you've done
* make sure your matview geometry column advertises the geometry type/srid of the column
So in your SQL query, you need to be explicit about the type/srid, like:
```sql
CREATE VIEW foobar AS   
  SELECT 
    ST_Buffer(geom, 10)::geometry(polygon, 3857) AS geom, 
    name, address 
  FROM addresses
```

**Comment by s8mathur** [comment]
Thank you for the prompt insight. Will give it a shot. Should `pointm` with an M value also work? 
```sql
::geometry(pointm, 4326)
```

**Comment by pramsey** [comment]
Should do.

**Comment by reyemtm** [comment]
Would is be possible to add materialized views as an option in the config, OR is there a way to enable them by default?

    relkind IN('r', 'v', 'm')
