### ISSUE TITLE
Change in Docker tags

### ISSUE THREAD

**Issue by baffioso** [CrunchyData/pg_tileserv#45]
Seems like latest and version tags on [dockerhub](https://hub.docker.com/r/pramsey/pg_tileserv) have been removed and  replaced with `CI`-tag. 

As of now `docker pull pramsey/pg_tileserv` fails beacuse of the missing latest tag.

Is `CI` going to be the only tag forward or are you planning to support latest/version tags again?

**Comment by pramsey** [comment]
Didn't realize 'latest' had special meaning, I've changed ci build to include that tag, hopefully will be better in a few minutes.

**Comment by baffioso** [comment]
Thanks for the quick fix and this awesome service!

Will you continue to support version tags on docker hub (eg. [20200612](https://hub.docker.com/layers/pramsey/pg_tileserv/20200612/images/sha256-c6fe609d5b1ba8040dd37abdc545aa666e528d39e68817c1a287105580fab8f8?context=explore))?

**Comment by pramsey** [comment]
Something about my docker build stopped applying tags to docker builds, so I need to get into it and fiddle ...
