### ISSUE TITLE
Feature wish: Set base path via env var

### ISSUE THREAD

**Issue by Jan-M** [CrunchyData/pg_tileserv#54]
Hi there,

we are trying your tile server and would for convenience need to set another base path for the URLs handled. This is due to moving it behind an oauth2 proxy that includes the path `/tileserver`.

Seems like a spot where the env var could easily injected.
https://github.com/CrunchyData/pg_tileserv/blob/master/main.go#L363

We could also propose a PR if you see this being accepted.

Thanks,
Jan

**Comment by pramsey** [comment]
Seems like a good PR to me. A env var ... do we already have a config
option? I think so. Been on other code too much lately!

**Comment by dr-jts** [comment]
Config option is [here](https://github.com/CrunchyData/pg_tileserv/blob/master/config/pg_tileserv.toml.example#L36).

**Comment by Jan-M** [comment]
I am not sure we speak about the same issue, which we now resolved by simply rebuilding patche pg tileserv.

Essentially requests reach pg_tileserv with additional path segment `/tileserver/` and thus yields page not found.
