### ISSUE TITLE
Non-Integer Primary Key

### ISSUE THREAD

**Issue by kraftto** [CrunchyData/pg_tileserv#67]
I'm using a dataset with UUID-style primary keys of type text. When I'm trying to open the preview in the web interface, the data is not shown and I get the following error message in the log:

```
WARN[0041] FEHLER: mvt_agg_transfn: Could not find column 'attr_gml_id' of integer type (SQLSTATE XX000) 
ERRO[0041] SQL error on xplansyn.xplan_bp_baugebietsteilflaeche/9/269/165.pbf
```
Does that mean the PK is expected to be integer? If so, it would be great to allow other data types.

**Comment by pramsey** [comment]
The MVT format only allows for integral unique ids, so there's no way to ever coerce your key into a tile. However, it should be possible to create id-less tiles when the PK is non-integral, so this is still an issue to be addressed.
