### ISSUE TITLE
Support for Reverse Proxies

### ISSUE THREAD

**Issue by jojonas** [CrunchyData/pg_tileserv#68]
I would like to run pg_tileserv in a different path than the webserver's root (`/`). I use a reverse proxy (Traeffik) for that. Unfortunately, the links to the preview pages as well as the `tileurl` in the layer metadata JSON file link to the wrong places in that case.

I see two possible solutions:
* Make the external path configurable
* Use relative paths (if the API permits it?)

**Comment by pramsey** [comment]
Is UrlBase not doing it for you?

https://github.com/CrunchyData/pg_tileserv/blob/master/config/pg_tileserv.toml.example#L35

There's also a fair amount of code dedicated to trying to figure out what address the proxy host is using and then use that for the base url automatically. Anyways, all that to say, this should work more better.

https://github.com/CrunchyData/pg_tileserv/blob/master/util.go#L71-L91

Any more detailed clues you can provide WRT what your proxy server is sending back / what tileserver is succeeding on / failing on, would be helpful.

**Comment by jojonas** [comment]
Yes, sorry, this works for me! I wasn't aware of the configuration honestly. Thank you!
