### ISSUE TITLE
Doc: Function Layers best served with plpgsql instead of sql

### ISSUE THREAD

**Issue by tomvantilburg** [CrunchyData/pg_tileserv#73]
The first example for a function layer uses an 'SQL' function instead of 'plpgsql'. In our experience (PG12, postgis 3.0.1) where we used a slightly extended version of the example (see below) this degrades performance because the planner seems to ignore the index when the SQL is run from the function.
It is solved by using plpgsql.

For completeness the SQL in the function used:

```
WITH
    bounds AS (SELECT ST_TileEnvelope($1, $2, $3) AS geom),
 mvtgeom AS (
   SELECT ST_AsMVTGeom(ST_Transform(t.geom,3857), bounds.geom) AS "geom",
       "color","class","zmin","zmax","relh"
   FROM polygons_zlevels t, bounds
   WHERE ST_Intersects(t.geom, ST_Transform(bounds.geom,28992))
            AND $1 BETWEEN t.zmin AND t.zmax -1
)
SELECT ST_AsMVT(mvtgeom, ''getmvt'')  FROM mvtgeom;
```

**Comment by pramsey** [comment]
Yes, I found similar performance issues with the hexagon function, but figured for the larger longer running functions they wouldn't be much/such a big deal. I've swapped all the examples over to plpgsql.
