### ISSUE TITLE
Dynamic conf file

### ISSUE THREAD

**Issue by rmaziere** [CrunchyData/pg_tileserv#76]
Hey Paul,
I would like to modify the configuration file on fly, for example, to change the httpPort and pass this conf to the app without saving on disk.
I tested with sed 's/{PORT}/1234/g' ./conf.toml to change on fly the listening port, this works, but I can't pass that to the app.
Do you have an idea about how to do that the best way ?
Thanks

**Comment by pramsey** [comment]
With the latest build, you should be able to use environment variables to do dynamic run-time configuration without editing the conf file.
```
export TS_HTTPPORT=9090
./pg_tileserv
```
```
INFO[0000] pg_tileserv latest                           
INFO[0000] Run with --help parameter for commandline options 
INFO[0000] Using config file: /Users/pramsey/Code/go/src/github.com/CrunchyData/pg_tileserv/config/pg_tileserv.toml 
INFO[0000] Serving HTTP  at http://0.0.0.0:9090/        
INFO[0000] Serving HTTPS at http://0.0.0.0:7801/        
INFO[0000] Using CoordinateSystem.SRID 3857 with bounds [-2.00375083427892e+07, -2.00375083427892e+07, 2.00375083427892e+07, 2.00375083427892e+07] 
INFO[0000] Connected as 'pramsey' to '' @ '/private/tmp' 
INFO[0000] Serving HTTP  at 0.0.0.0:9090                
INFO[0000] Serving HTTPS at 0.0.0.0:7801                
```

**Comment by rmaziere** [comment]
Sorry, my explanation was not clear enough.
I would like to run multiple instances of pg_tileserv on the same server. This is the reason why I have to pass a different port value to each instance.
The best solution might be:
- a configuration file with all the common parameters,
- some parameters in the command line to override the configuration file.

**Comment by rmaziere** [comment]
Sorry, my explanation was not clear and complete enough.
I would like to run multiple instances of pg_tileserv on the same server. This is the reason why I have to pass a different port value to each instance.
For my case, the best solution might be:
- a configuration file with all the common parameters,
- some parameters in the command line to override the configuration file.
How can I do that ?
Thanks

**Comment by pramsey** [comment]
Each instance you start can have a separate environment, I'm not sure what adding a cmdline provides?

**Comment by rmaziere** [comment]
I'm sorry, but I don't understand how I can have separate environment.
If I have : 
```sh
ls ./pg_tileserv
pg_tileserv    pg_tileserv.toml
```
and I would like to launch 2 instances on 7800 and 7803, I can't use the same conf file because of the port.
Right now, in dev env, the solution I use is to have one conf file for each instance, but this is not a spotless work.

**Comment by pramsey** [comment]
The environment variable over-rides the config file, so you have one file, and you switch the environment variable before you start the process.
