### ISSUE TITLE
Can't display tiles 

### ISSUE THREAD

**Issue by BriacR** [CrunchyData/pg_tileserv#77]
Hello guys, 

I am trying to call my pg_tileserver via a leaflet html but I am getting this error could someone help me out ?

Sorry for the newbie question.
`
INFO[1002] GET /public.ne_50m_admin_0_countries/2/3/0.pbf  method=GET url=/public.ne_50m_admin_0_countries/2/3/0.pbf
ERRO[1002] Unable to get layer 'public.ne_50m_admin_0_countries'
`

**Comment by pramsey** [comment]
Well, you'd (a) need to have a table in the public scheme named ne_50m_admin_0_countries, right? And (b) you need to have hit the index page at least once since you loaded that table or the server won't know it is there.

**Comment by pramsey** [comment]
Also note the minimum requirements for a table to be published, particularly the need to have a declared geometry type and srid https://github.com/crunchydata/pg_tileserv#table-layers

**Comment by louisguitton** [comment]
> Also note the minimum requirements for a table to be published, particularly the need to have a declared geometry type and srid https://github.com/crunchydata/pg_tileserv#table-layers

great shout, great doc. I noted a few more things while investigating:

- there is also this function which is equivalent to the `ALTER TABLE` DDL in the docs
  ```sql
  select UpdateGeometrySRID('my_table', 'geom', 2154);
  ```
- because you need to alter a column type, this won't work on Views, only on Tables
- the `st_setsrid` function seemed like a way to do all in 1 step instead of 2 but ended up not working
  ```sql
  create table my_table as (
  	select
		titre,
		num_dep :: int as code_departement,
		count(geom) as count,
		st_setsrid(st_collect(geom), 2154) as geom -- doesn't work, you still need to alter the table after
	from raw.scan25
  )
  ```

**Comment by pramsey** [comment]
You should be able to one-step it, but you need to include a little extra metadata for the query:
```sql
create table my_table as
	select
  	titre,
  	num_dep :: int as code_departement,
  	count(geom) as count,
  	st_setsrid(st_collect(geom), 2154)::geometry(multipoint, 2154) as geom
  from raw.scan25
```

**Comment by louisguitton** [comment]
thank you sir, this works.
