### ISSUE TITLE
multiple projection support

### ISSUE THREAD

**Issue by hannesaddec** [CrunchyData/pg_tileserv#83]
is there a way to configure multiple projections (e.g. EPSG:4326,3857,3035) in one instance ?

**Comment by pramsey** [comment]
No, right now it's service-wide. Can always run a second instance.

**Comment by hannesaddec** [comment]
Second instance - ok, 
@pramsey - would you accept a PR trying to get multiple SRID out/configurable?

**Comment by pramsey** [comment]
What would the implementation look like?

**Comment by hannesaddec** [comment]
not really looked into it how to implement.   
1) You can specify at config level a range of supported EPSG codes/boxes. - e.g. similar what mapproxy does -> https://mapproxy.org/docs/latest/configuration.html -> Example grids configuration
2) At URL/endpoint level you could add &srs=EPSG%3A3035 and the data would be delivered in 3035. If no srs is specified it would fall back to default or first defined SRS. 
Reason why doing that at server side - Save energy (our planet) as we do it once - Otherwise everyone which makes a non 3857 webmap would need to reproject it on the fly in the browser

**Comment by pramsey** [comment]
So the reason to resist this, from a product point-of-view is that 99% of app builders build their app around a single projection (and 99% of **those** people use 3857). So adding the features complicates the code base in the service of a very narrow user base. Why is it you see this as a need? Someone wrote you a spec that said "web map must support these 5 projections"? Something else?

**Comment by hannesaddec** [comment]
We see also in our services that 3857 is the mostly used projection (90%), but  
Why we see the need: As soon as you show statistical data aggregated on an area - 3857 is not an appropriate  projection - to support this users base.  
No
No

**Comment by pramsey** [comment]
So, the difficulty, and the reason that we don't just support an arbitrary client-side EPSG code is that we need not only a destination coordinate system, but also a destination **extent**. We need a square extent for tile zoom 0 from which to start the tile pyramid, and that information is not implicit in the EPSG code or even in the EPSG database. That implies that, as for our single-projection support, we'd need lots and lots of entries in the configuration file. Which is ugly.
While 3857 is not an appropriate projection for calculating areas, I don't really see why it's so bad for displaying the correct results of such calculations (which you could do in the back-end, using appropriate projections or geodetics). What are you displaying that would not work with Mercator?

**Comment by hannesaddec** [comment]
We know that.. defining these extents and exposing them to the outside users is the most challenging - we have done so for 3035.. the user would need to define these 
1) certain EPSG are default
2) custom defined projection you have something like
grids:
  germany:
    srs: 'EPSG:25832'
    bbox: [6, 47.3, 15.1, 55]
    bbox_srs: 'EPSG:4326'
    res: [1, 0.5, 0.25, 0.125, 0.0625]

On the 3857 - this is old discussion which we should not discuss (starting with old papers from 1943 https://www.jstor.org/stable/209913?seq=1) , my recent best on is the Kenneth Field quote "Put simply, Web Mercator kills thematic maps."
