### ISSUE TITLE
Vector tile - line dash rendering issue in MapBox GL-JS

### ISSUE THREAD

**Issue by zsoooc** [CrunchyData/pg_tileserv#84]
I'm developing a MapBox GL-JS application (v1.13, but I triad also with v2). The source is vector tile published by pg_tileserv (current version, default config) and I faced with a problem regarding the rendering. I want to display railway lines in high zoom level (20-22). I have one source, with two layers. 
The first is a black line, the second one is a white, dashed line. It's important that the line geometries are long, so on the pictures, there are no connecting points.

The problem is the rendering quality. See the images below. The first is a view with pitch: 60, the pitch of the second one is 0.

What do you think? Do you have any suggestions how to fix it? Or is it a bug in pg-tileserv or in MapBox?

This is my code:

```
 var vectorServer = "http://localhost:7800/";
 var vectorSourceLayer = "france.railways_osm_3857";
var vectorUrl = vectorServer + vectorSourceLayer + "/{z}/{x}/{y}.pbf";

map.addSource('railways', {
'type': 'vector',
'tiles': [vectorUrl],
'minzoom': 13,
'maxzoom': 22
});

map.addLayer({
'id': 'railways',
'type': 'line',
'source': 'railways','source-layer': 'railways_osm',
"paint": {
'line-width':20,
'line-color': '#000000'
}
});
```

```
map.addLayer({
'id': 'railways2',
'type': 'line',
'source': 'railways','source-layer': 'railways_osm',
"paint": {
'line-width':15,
'line-dasharray':[5,10],
'line-color': '#ffffff'
}
});
```
![HwGWn](https://user-images.githubusercontent.com/19270270/110350202-c2833c00-8033-11eb-8139-7609da6b137c.png)
![YMrJD](https://user-images.githubusercontent.com/19270270/110350206-c31bd280-8033-11eb-9cc6-028429776d55.png)

**Comment by pramsey** [comment]
We just provide the raw data, the rendering is up to the client. If as you say the examples are all maximum length then the only possible data issue (which is really a rendering issue) is "rendering a linear style across linear feature boundaries".
