### ISSUE TITLE
Only one geometry column per table exposed as a layer

### ISSUE THREAD

**Issue by apjoseph** [CrunchyData/pg_tileserv#85]
Given the following table:
```pgsql
DROP TABLE IF EXISTS example.test_two_geom_cols;
CREATE TABLE example.test_two_geom_cols(
    id uuid PRIMARY KEY,
    centroid geometry(Point,4326),
    geom geometry(MultiPolygon,4326)
);
```

#### Expected Behavior

pg_tileserv exposes both geometry columns as separate layers with identifiers like:
`example.test_two_geom_cols.centroid`
`example.test_two_geom_cols.geom`

#### Actual Behavior
pg_tileserv chooses the first geometry column defined in the table for the layer

**Comment by douglasg14b** [comment]
This is a use case I have as well. I have polygons, and also the center points in the same table, with the idea being that I would be serving up the points layer at wider zoom levels. But it only exposes one :(

A function could do this maybe?

**Comment by pramsey** [comment]
Yeah, the MVT format only understands the idea of one geometry column at a time. The most that could be done (and I hesitate to do it, as it would be very ugly) would be to stuff one of the columns into an attribute as a text string. This would quite brutally fluff up the attribute dictionaries and impact tile size very negatively, so... 
Anyways, yes, a function is ever and always the best way to get precisely tuned behaviour from this app -- the direct table access will always be a lowest-common-denominator affair.

**Comment by dr-jts** [comment]
Can this be done with a view?
```sql
CREATE VIEW centroids AS
SELECT id, centroid FROM example.test_two_geom_cols;
```
