### ISSUE TITLE
Specify PostGIS installation schema in the toml config file ?

### ISSUE THREAD

**Issue by Captain-Oski** [CrunchyData/pg_tileserv#87]
Hey guys, 

I was just wondering, for technical reason we installed postgis in a `postgis` schema.

We cannot have it in the search_path.

Pg_tileserv seems to read only for the schemas in the search path.

Would there be an easy way to make this a new variable in the toml config file ?

Thank you and keep up the amazing work.

**Comment by pramsey** [comment]
```
ALTER DATABASE mydatabase SET search_path = public, postgis
```
or maybe something specific to tileserv?
```
ALTER USER pg_tileserv SET search_path = public, postgis
```
Can you explain why you cannot have it in search path?

**Comment by Captain-Oski** [comment]
Sorry for the misunderstanding. 

Let's make it more clear : 

We are connecting the pg_tileserv instance to a distant database on which we have no superuser privilege.

Our postgresql instance have 2 spatial extensions (ArcSDE and Postgis) each installed on a specific schema. (sde, postgis)

As ArcSDE and PostGIS share some similar named function eg  : sde.st_area and postgis.st_area I think this will kind of break the stack.

Having already sde in the search path, we can't have both ( My guess ), and sde **must** be set in the search_path.

This is why I would think of having a parameter in the toml config file.

Thank you for your quick answer btw.

**Comment by Captain-Oski** [comment]
I guess I could submit a small PR for that if you would accept such a feature.

**Comment by pramsey** [comment]
I really want to avoid configuration explosion, so if there's ways to work around these things I prefer them. I don't see any benefit to doing a fully-qualified references to everything, so at most the ability to set the search path for the duration of a connection. Come to think of it, that might be available just via the connection string as an option.

**Comment by Captain-Oski** [comment]
> I really want to avoid configuration explosion, so if there's ways to work around these things I prefer them. I don't see any benefit to doing a fully-qualified references to everything, so at most the ability to set the search path for the duration of a connection. Come to think of it, that might be available just via the connection string as an option.

Thank you for pointing that out ! 

For others the having the same issue, you can as @pramsey pointed out specify the schema (search_path) in the connection string !

eg : postgresql://USER:PASSWORD@URL/DATABASENAME?search_path=postgis,[...otherSchemas]

This is working out well.

👍

**Comment by pramsey** [comment]
Yay, thanks for the reference, good knowledge to have.
