### ISSUE TITLE
How to configure pg_tileserv with Varnish for caching?

### ISSUE THREAD

**Issue by Guiming** [CrunchyData/pg_tileserv#88]
Could you show how to configure a caching service for pg_tileserv?
I wanted to use Varnish along with pg_tileserv to improve performace, but do not know how to hook up the two together.
Thanks in advance.

**Comment by pramsey** [comment]
https://blog.crunchydata.com/blog/production-postgis-vector-tiles-caching

**Comment by Guiming** [comment]
@pramsey Thanks for replying!
I did read that blog. However, it did not help as I am simply not familiar with Docker Compose (nor using Docker). I am running a Ubuntu 20.04 system. I'd like to know how to set up various things in the configuration files (of pg_tileserv and Varnish) to make caching work.
Any specific instruction, or pointer to tutorials/resources would be greatly appreciated.

**Comment by pramsey** [comment]
Sorry, you're just going to have to read through the varnish docs. There's nothing special about pg_tileserv as an http service, standard varnish setup should be fine.
