### ISSUE TITLE
Controlling min & max zoom on a per layer basis

### ISSUE THREAD

**Issue by rowanwins** [CrunchyData/pg_tileserv#91]
From what I can tell at the moment pg_tileserv only has a single global config for `DefaultMinZoom` and `DefaultMaxZoom`. However it would be handy to be able to set minZoom and maxZoom on a layer by layer basis. 

Using [Table Tile Request Customizations](https://github.com/CrunchyData/pg_tileserv#table-tile-request-customization) you can override various parts of the global config like `MaxFeaturesPerTile` for an individual layer by attaching query params  like http://localhost:7800/public.ne_50m_admin_0_countries/{z}/{x}/{y}.pbf?limit=10000
However I'm not sure if it makes sense to use url params to achieve the same for min and max zoom... for example one potential limitation I could see with that is that the minzoom and maxzoom are advertised in the layer json endpoint...

I wonder if they could be stored and retrieved from table comments similarly to what is done for the column comments?

Any thoughts?

**Comment by pramsey** [comment]
Once we start parsing the table comments things start getting very squirrely... I rather assumed that the web client would take some responsibility for making sure the right things were shown at the right time. All the server can do when asked for a tile that is out of range is ... serve an empty tile. Which is probably not the best way to get multi-scale data?
I always thought about multi-scale as something that might be done in a function, where the source of data for the tile is switched based on zoom level... sometimes switching tables, sometimes applying "where" clauses, and so on.
I guess the operational utility of this is to prevent people from calling for level 0 tiles from very large tables, causing a sequential scan that just ends up in the server dropping all but MaxFeatures of the data. Hm.

**Comment by rowanwins** [comment]
Yeahs its a bit of a prickly one...

Client libraries like mapbox-gl let you set a min and max zoom level for requesting tiles from a given source, but that doesn't prevent front-end devs from doing silly things and flogging the server by requesting property parcels at zoom level 1 because the pg_tileserv allows it (because you want some other point layer available at zoom level 1).

In this case it's not so much about multi-scale data and so going down the function route seems like overkill.

Perhaps another option would be reading some layer config from the existing toml file? eg
````
DefaultMinZoom = 10
[Layers]
[Layers.parcels]
MinZoom = 15
[Layers.cities]
MinZoom = 1
````

**Comment by dr-jts** [comment]
> Perhaps another option would be reading some layer config from the existing toml file? 

The other option we've kicked around is a layer metadata table.  In keeping with the "database as config" philosophy.
