### ISSUE TITLE
Binary builds for specific version?

### ISSUE THREAD

**Issue by zmbc** [CrunchyData/pg_tileserv#92]
First of all, thanks for pg_tileserv! It's great.

The README links to a binary build of the latest version, which is super convenient because I don't have to install Go. But as far as I can tell, this is overwritten at https://postgisftw.s3.amazonaws.com/pg_tileserv_latest_{platform}.zip every time there is a new release. And the only downloads available on [the Releases page](https://github.com/CrunchyData/pg_tileserv/releases/tag/v1.0.8) are of un-built source code. Would it be possible to make builds available on a per-version basis?

(As a side note, I am also using the [Docker Hub images](https://hub.docker.com/r/pramsey/pg_tileserv/tags?page=1&ordering=last_updated) and it would be helpful if they also were available on a per-version basis.)

Cheers!

**Comment by pramsey** [comment]
I've tried to keep to at latest-is-the-bestest policy, why do you need versioned stuff?

**Comment by zmbc** [comment]
@pramsey I don't really _need_ it, but here's why it would be nice:

I'm using Docker in production with an image based on the Docker Hub image. In development, I can run the app in a Docker container, but I'd like to run it without the overhead and without needing to restart it to pick up `assets` changes.

Given the above setup, in development I can be running a different version than I am using Docker. This bit me recently when re-downloading pg_tileserv after [this change](https://github.com/CrunchyData/pg_tileserv/commit/9b94c47ee07b1728cbee979f23ae72236c64abe9#diff-8f44a03e933b56fda430003ddb8ff6653e64dac7e2f9bb7b5473e233807ef868L26-R26) caused my development run to fail with an old `assets/index.html` while my Docker image was continuing to work fine. Took me a while to even realize what the difference was between them.

Totally understand if it's not something you want to support, but that is the reason why I would like it.
