### ISSUE TITLE
Styling in Angular ngx-leaflet

### ISSUE THREAD

**Issue by cscrumconsulting** [CrunchyData/pg_tileserv#95]
I'm using the tile server and my front end is an Angular 10.x application using ngx-leaflet. I have loaded the vectorgrid extension and I can get the vector tiles to show on the map, but none of the styling I apply is showing up. I just get blue circles for points and blue lines for lines and polygons. Has anyone successfully applied styles in angular? Below is my code:

`buildTileLayer(tilename,group){
    var self = this;
    var renderer = L.canvas({padding:0.5});
    var tileurl = 'http://192.53.167.179/telecom.' + tilename ;
    var vectorTileStyling = {};
    var vectorTileColor = "green";
    vectorTileStyling['telecom.' + tilename] = {
      fill: true,
      fillColor: vectorTileColor,
      fillOpacity: 0.1,
      color: vectorTileColor,
      opacity: 0.7,
      weight: 2
    };

    var vectorTileOptions = {
      vectorTileLayerStyles: {
          vectorTileStyling
      },
      renderer: renderer,
      zIndex: 1000,
      interactive: true // Make sure that this VectorGrid fires mouse/pointer events
    };

    var tlayer = L.vectorGrid.protobuf(tileurl + '/{z}/{x}/{y}.pbf', {
      vectorTileOptions
    });
    
    tlayer['name'] = tilename;
    self.allOverlays[tilename] =  tlayer;

    // checks for user settings and visibility and adds layers to map based on user settings
     self.buildprojectLayercontrol(tilename);
}

`

**Comment by pramsey** [comment]
Should we have a discourse instance or something for discussion of these kind of user-oriented questions? It's almost orthogonal to tiles, maybe it's better to ask a leaflet forum?
