### ISSUE TITLE
Not exposing all tables

### ISSUE THREAD

**Issue by henriktorget** [CrunchyData/pg_tileserv#98]
Hey! 

I love pg_tileserv!

I have a table in public that looks like this:
![image](https://user-images.githubusercontent.com/5030524/122206235-69803b00-cea1-11eb-938d-cafe01483ec6.png)

But i cant see it being served from pg_tileserv. 
I have given access to the schema and table, but it's not showing up after restarting the server.
Other tables are working fine.

Any ideas to where i can look?

POSTGIS="2.5.3 r17699" [EXTENSION] PGSQL="96" GEOS="3.7.2-CAPI-1.11.0 3.7.2" SFCGAL="1.3.2" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.2.4, released 2018/03/19 GDAL_DATA not found" LIBXML="2.7.8" LIBJSON="0.12" LIBPROTOBUF="1.2.1" RASTER

**Comment by pramsey** [comment]
Probably the geometry column doesn't have explicit type and srid? (ps, upgrade to more recent postgis for much improved performance). Fill in the correct type and srid for  your geometr.
```
alter table mytable alter column geom type Geometry(Point, 4326)
```

**Comment by henriktorget** [comment]
I'd love to upgrade postGIS but 2.5 is the newest version availiable in Azure 👎.
Will try this today, thanks a lot for the explanation.

**Comment by henriktorget** [comment]
Yep this did the trick! Thanks @pramsey. Listening to you on The Mapscaping podcast right now 😄

**Comment by adamtimm** [comment]
> I'd love to upgrade postGIS but 2.5 is the newest version availiable in Azure 👎. Will try this today, thanks a lot for the explanation.

If you're looking for an alternative to PostGIS in Azure that allows you to upgrade to the latest version of PostGIS while deploying to you're Azure account, check out https://www.crunchydata.com/products/crunchy-bridge/.
